### ISSUE TITLE
serialisation to md file should preserve order of the fields

### ISSUE THREAD

**Issue by mcourtot** [ga4gh-metadata/SchemaBlocks#3]
See https://github.com/ga4gh-metadata/schemas/blob/master/main/doc/individual.md

Ideally we'd have created and updated together at the end

**Comment by mbaudis** [comment]
Oh my... We can introduce an ordered list for attributes in the YAML header, or in the script. Could be partial (e.g. "things at the end"), so modifications don't have to be tracked at 2 places? (But confusing since then alphabetical & extra).

**Comment by mbaudis** [comment]
I've added a separate option to the class definitions for [ordering attributes](https://github.com/ga4gh-metadata/schemas/blob/master/main/yaml/biosample.yaml#L12 ). However, I haven't had time to do this for all...

But this currently only applies to the YAML -> MD conversion; JSON isn't affected, since it is just a dumping of the structure & does not preserve the original order. 

The easiest way would be to have the properties as list, not dictionary, which would keep the order:

```
    properties:
      - id:
          type: ...
          description: ...
          example: ...
      - project_id:
          type: ...
          description: ...
          example: ...
```
instead of 
```
    properties:
      id:
        type: ...
        description: ...
        example: ...
      project_id:
        type: ...
        description: ...
        example: ...
```

But I don't know enough about the formalities here?
